### ISSUE TITLE
好像失效了

### ISSUE THREAD

**Issue by 007ayong** [oneNorth7/Cloud189_popper#1]
在单文件分享界面，无解除限制提示，点击下载按钮会提示下载客户端。
主页会提示加载超时，刷新后也不太行。

**Comment by loadingfd** [comment]
+1

**Comment by oneNorth7** [comment]
6月16日天翼云官方进行了**升级改版**，导致脚本**暂时失效**，greasyfork页面和微信公众号有发了紧急通知，github最近上传一直有问题就没更新通知；**本人正在抓紧时间分析寻找突破口，敬请期待！**

**Comment by oneNorth7** [comment]
上传同步还是失败，新脚本已发布在greasyfork上，可前往[雷利子](https://greasyfork.org/zh-CN/scripts/424022-%E9%9B%B7%E5%88%A9%E5%AD%90)脚本页面安装
