### ISSUE TITLE
建议直接去掉个人主页的目录树切换按钮

### ISSUE THREAD

**Issue by 007ayong** [oneNorth7/Cloud189_popper#2]
看到 README 中提到了个人主页中使用目录树会有问题，是不是可以考虑直接去掉该按钮，禁用该功能

**Comment by oneNorth7** [comment]
> 看到 README 中提到了个人主页中使用目录树会有问题，是不是可以考虑直接去掉该按钮，禁用该功能

感谢建议，在后续版本会考虑把目录树按钮隐藏。

**Comment by oneNorth7** [comment]
已更新版本，支持目录树切换目录自动突破下载限制，故无需隐藏此按钮。
